version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: dev_db
    environment:
      POSTGRES_USER: dev_db
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    volumes:
      - ./database/development/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432