spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    # url: ${JDBC_DATABASE_URL}
    # username: ${JDBC_DATABASE_USERNAME}
    # password: ${JDBC_DATABASE_PASSWORD}
    # local docker database
    url: jdbc:postgresql://localhost:5432/dev_db?currentSchema=dev_db
    username: dev_db
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /api
